// GENERATED by src/data/LayoutsWgsl.ts from src/data/Layouts.ts. Do not edit.
// Binding contract version 3.

// size 104, align 8
struct Frame {
  originHi : vec2<f32>,           // @0  camera centre, high part
  originLo : vec2<f32>,           // @8  camera centre, low part
  scale : vec2<f32>,              // @16  world units -> NDC, includes aspect
  rotation : vec2<f32>,           // @24  cos, sin
  viewportPx : vec2<f32>,         // @32
  invViewportPx : vec2<f32>,      // @40
  pixelRatio : f32,               // @48
  zoom : f32,                     // @52  device px per world unit
  time : f32,                     // @56  seconds since init, for animated hooks
  frameIndex : u32,               // @60
  pointerPx : vec2<f32>,          // @64  cursor, device px; (-1,-1) if outside
  rasterDim : vec2<u32>,          // @72  accumulation buffer dimensions
  nodeCount : u32,                // @80
  edgeCount : u32,                // @84
  globalNodeScale : f32,          // @88
  globalEdgeWidth : f32,          // @92
  flags : u32,                    // @96  FRAME_* bits
  globalEdgeColor : u32,          // @100  rgba8unorm tint for edges with no per-edge colour
}

@group(0) @binding(0) var<uniform> frame : Frame;
@group(0) @binding(1) var samp_linear : sampler;
@group(0) @binding(2) var samp_nearest : sampler;

@group(1) @binding(0) var<storage, read> nodePos : array<vec2<f32>>;
@group(1) @binding(1) var<storage, read> nodeStyle : array<u32>;
@group(1) @binding(2) var<storage, read> nodeSize : array<u32>;               // size f16 low half, icon colour index high half
@group(1) @binding(3) var<storage, read> nodeColor : array<u32>;              // rgba8unorm
@group(1) @binding(4) var<storage, read> nodeState : array<u32>;              // STATE_* bits
@group(1) @binding(5) var<storage, read> edgeIdx : array<vec2<u32>>;
@group(1) @binding(6) var<storage, read> edgeStyle : array<u32>;
@group(1) @binding(7) var<storage, read> edgeColor : array<u32>;

const STATE_HOVERED : u32 = 1u;
const STATE_SELECTED : u32 = 2u;
const STATE_DIMMED : u32 = 4u;
const STATE_HIDDEN : u32 = 8u;
const STATE_NEIGHBOR : u32 = 16u;
const STATE_DRAGGING : u32 = 32u;
const STATE_FOREGROUND_MASK : u32 = 0x23u;
const STATE_GROUP_SHIFT : u32 = 8u;
const STYLE_SHAPE_MASK : u32 = 0xFFu;
const STYLE_ICON_SHIFT : u32 = 8u;
const STYLE_ICON_MASK : u32 = 0xFFFFu;
const STYLE_ZLAYER_SHIFT : u32 = 24u;
const STYLE_ZLAYER_MASK : u32 = 0xFu;
const Z_LAYERS : u32 = 16u;
const STYLE_FLAGS_SHIFT : u32 = 28u;
const STYLE_FLAG_RING : u32 = 0x10000000u;
const STYLE_FLAG_LABEL : u32 = 0x20000000u;
const STYLE_FLAG_PINNED : u32 = 0x40000000u;
const NO_ICON : u32 = 0xFFFFu;
const SIZE_ICON_COLOR_SHIFT : u32 = 16u;
const SHAPE_CIRCLE : u32 = 0u;
const SHAPE_SQUARE : u32 = 1u;
const SHAPE_HEXAGON : u32 = 2u;
const INSTANCE_SHAPE_BITS : u32 = 15u;
const INSTANCE_LAYER_SHIFT : u32 = 4u;
const INSTANCE_LAYER_BITS : u32 = 240u;
const EDGE_WIDTH_MASK : u32 = 0xFFu;
const EDGE_CURVE_SHIFT : u32 = 8u;
const EDGE_CURVE_MASK : u32 = 0xFu;
const EDGE_CURVATURE_SHIFT : u32 = 12u;
const EDGE_CURVATURE_MASK : u32 = 0xFFu;
const EDGE_ZLAYER_SHIFT : u32 = 20u;
const EDGE_CAP_SHIFT : u32 = 24u;
const EDGE_FLAG_DIRECTED : u32 = 0x10000000u;
const EDGE_FLAG_DASHED : u32 = 0x20000000u;
const EDGE_WIDTH_SCALE : u32 = 8u;

override WORKGROUP_SIZE : u32 = 256u;
override RASTER_TILE_X : u32 = 1u;
override RASTER_TILE_Y : u32 = 1u;
override ENABLE_RINGS : bool = true;
override ENABLE_GRADIENT_EDGES : bool = true;
override SMALL_NODE_PX : f32 = 3.0;
override LOD_TARGET_PX : f32 = 2.5;
override SMALL_EDGE_PX : f32 = 1.5;
override USER_WORDS : u32 = 0u;

// ---- Engine-internal (not public contract; may change between versions) ----

// size 16, align 8
struct NodeInstance {
  screenPos : vec2<f32>,          // @0  device px
  radiusPx : f32,                 // @8  projected radius, device px; low INSTANCE_SHAPE_BITS mantissa bits hold the shape, INSTANCE_LAYER_BITS the z layer
  color : u32,                    // @12  rgba8unorm
}

// size 24, align 8
struct ChunkBounds {
  lo : vec2<f32>,                 // @0  min node centre, world
  hi : vec2<f32>,                 // @8  max node centre, world
  maxSize : f32,                  // @16  largest diameter, world, before globalNodeScale
  flags : u32,                    // @20  CHUNK_FLAG_* bits
}

// size 48, align 8
struct EdgeChunk {
  lo : vec2<f32>,                 // @0  min endpoint, world
  hi : vec2<f32>,                 // @8  max endpoint, world
  maxLen : f32,                   // @16  longest edge, world units
  maxWidthPx : f32,               // @20  widest per-edge style width, device px; 0 = none
  density : f32,                  // @24  edge length per area where this length level lies, 1/world
  _pad : f32,                     // @28
  midLo : vec2<f32>,              // @32
  midHi : vec2<f32>,              // @40
}

const EDGE_CHUNK_SIZE : u32 = 1024u;
const EDGE_CHUNK_SHIFT : u32 = 10u;
const EDGE_CHUNK_WORDS : u32 = 12u;
const EDGE_LEVEL_BITS : u32 = 4u;
const EDGE_SCRATCH_DRAW_ARGS : u32 = 0u;
const EDGE_SCRATCH_DISPATCH : u32 = 4u;
const EDGE_SCRATCH_LIST_COUNT : u32 = 7u;
const EDGE_SCRATCH_LIST : u32 = 8u;

// size 92, align 4
struct LabelParams {
  textH : f32,                    // @0
  labelH : f32,                   // @4
  gap : f32,                      // @8
  padding : f32,                  // @12
  maxHalfW : f32,                 // @16
  maxHalfH : f32,                 // @20
  minEdgeW : f32,                 // @24
  labelArea : f32,                // @28
  cellW : f32,                    // @32
  bonus : f32,                    // @36
  fadeS : f32,                    // @40
  glyphTable : u32,               // @44
  gridW : u32,                    // @48
  gridH : u32,                    // @52
  capacity : u32,                 // @56
  chunks : u32,                   // @60
  levels : u32,                   // @64
  nodeCount : u32,                // @68
  edgeChunks : u32,               // @72
  edgeLevels : u32,               // @76
  edgeCount : u32,                // @80
  bitsOffset : u32,               // @84
  liveCount : u32,                // @88
}

// size 32, align 8
struct LabelCandidate {
  center : vec2<f32>,             // @0
  halfW : f32,                    // @8
  halfH : f32,                    // @12
  rank : f32,                     // @16
  index : u32,                    // @20
  size : f32,                     // @24
}

// size 20, align 4
struct LiveLabel {
  index : u32,                    // @0
  slot : u32,                     // @4
  run : u32,                      // @8
  start : f32,                    // @12
  fadeOut : u32,                  // @16
}

const LABEL_NONE : u32 = 0xFFFFFFFFu;
const LABEL_EDGE_BIT : u32 = 0x80000000u;
const LABEL_GLYPHS : u32 = 32u;
const LABEL_TREE_TOP : u32 = 16u;
const LABEL_ROUNDS : u32 = 8u;
const LABEL_NEIGHBOURS : u32 = 48u;
const LABEL_LANES : u32 = 8u;
const LABEL_SHOWN_MAX : u32 = 4096u;
const LABEL_SLOTS : u32 = 8192u;
const LABEL_GLYPH_MAX : u32 = 8192u;
const WORK_CANDIDATES : u32 = 0u;
const WORK_JOBS : u32 = 1u;
const WORK_SHOWN : u32 = 2u;
const WORK_ROUND : u32 = 3u;
const WORK_EDGE_JOBS : u32 = 12u;
const WORK_MAX_HALF_W : u32 = 13u;
const WORK_MAX_HALF_H : u32 = 14u;
const WORK_JOB_LIST : u32 = 16u;
const LABEL_EDGE_PARTS : u32 = 2u;
const LABEL_LIST_PARTS : u32 = 4u;
const ARGS_JOBS : u32 = 0u;
const ARGS_EDGE_JOBS : u32 = 1u;
const ARGS_LISTS : u32 = 3u;
const ARGS_ROUND : u32 = 7u;

const BUCKET_NORMAL : u32 = 0u;
const BUCKET_FOREGROUND : u32 = 1u;
const BUCKET_TINY : u32 = 2u;
const BUCKET_CLUSTER : u32 = 3u;
const BUCKET_CULLED : u32 = 0xFu;
const NUM_BUCKETS : u32 = 4u;
const ITEMS_PER_THREAD : u32 = 4u;
const CHUNK_SIZE : u32 = 1024u;
const DRAW_SEGMENT : u32 = 16u;
const CHUNK_FLAG_FOREGROUND : u32 = 0x1u;
const CHUNK_BOUNDS_WORDS : u32 = 6u;
const SCRATCH_DRAW_ARGS : u32 = 0u;
const SCRATCH_BUCKET_BASE : u32 = 16u;
const SCRATCH_LIST_COUNT : u32 = 20u;
const SCRATCH_ICON_BASE : u32 = 21u;
const SCRATCH_ICON_COUNT : u32 = 22u;
const SCRATCH_CHUNKS : u32 = 32u;
const RADIX_BITS : u32 = 4u;
const RADIX_BINS : u32 = 16u;
const MOVE_COUNT : u32 = 0u;
const MOVE_NODE : u32 = 1u;
const MOVE_LIST : u32 = 2u;
const MOVE_GROUPS : u32 = 256u;

// size 24, align 8
struct PickParams {
  pointer : vec2<f32>,            // @0
  radiusPx : f32,                 // @8
  flags : u32,                    // @12
  edgeRadiusPx : f32,             // @16
}

const PICK_NODE_COUNT : u32 = 0u;
const PICK_EDGE_BEST : u32 = 1u;
const PICK_NODE_RESULT : u32 = 2u;
const PICK_EDGE_RESULT : u32 = 3u;
const PICK_EDGE_COUNT : u32 = 4u;
const PICK_NODE_SCALE : u32 = 5u;
const PICK_NODE_ENGINE : u32 = 6u;
const PICK_LIST : u32 = 8u;
const PICK_FLAG_NODES : u32 = 0x1u;
const PICK_FLAG_EDGES : u32 = 0x2u;
const PICK_FLAG_SHAPES : u32 = 0x4u;
const PICK_FLAG_EDGE_COLORS : u32 = 0x8u;
const PICK_FLAG_LAYERS : u32 = 0x10u;
const PICK_LAYER_SHIFT : u32 = 27u;
const HOVER_FLAG_SHAPES : u32 = 0x1u;

// size 48, align 4
struct HoverParams {
  node : u32,                     // @0
  lodScale : f32,                 // @4
  nodeOutlineScale : f32,         // @8
  nodeOutlineColor : u32,         // @12
  edgeA : u32,                    // @16
  edgeB : u32,                    // @20
  edgeStyle : u32,                // @24
  edgeColor : u32,                // @28
  edgeWidth : f32,                // @32
  flags : u32,                    // @36
  nodeOutlineMinPx : f32,         // @40
  nodeOutlineMaxPx : f32,         // @44
}

const ICON_TILE : u32 = 64u;
const ICON_HEADER_WORDS : u32 = 4u;
const ICON_RECORD_WORDS : u32 = 4u;
const ICON_CURVE_WORDS : u32 = 6u;
const ICON_BANDS_MASK : u32 = 0xFFFFu;
const ICON_FLAG_EVEN_ODD : u32 = 0x10000u;
const ICON_PALETTE_WIDTH : u32 = 256u;
const ICON_WORD_ID_MASK : u32 = 0xFFFFu;
const ICON_WORD_COLOR_SHIFT : u32 = 16u;
