/**
 * Emits `src/shaders/common/layouts.wgsl` from `Layouts.ts`.
 * Run through `npm run gen`; a unit test asserts the checked-in file is current.
 */
import {
  BINDING_CONTRACT_VERSION,
  CHUNK_BOUNDS,
  CONSTANTS,
  EDGE_CHUNK,
  EDGE_CONSTANTS,
  ENGINE_CONSTANTS,
  FRAME,
  FRAME_BINDINGS,
  GRAPH_BINDINGS,
  GROUP_FRAME,
  GROUP_GRAPH,
  HOVER_PARAMS,
  LABEL_CANDIDATE,
  LABEL_CONSTANTS,
  LABEL_PARAMS,
  LIVE_LABEL,
  NODE_INSTANCE,
  OVERRIDES,
  PICK_CONSTANTS,
  PICK_PARAMS,
  type BindingDef,
  type StructLayout,
} from "./Layouts";

function emitStruct(s: StructLayout): string {
  const lines = s.fields.map((f) => {
    const decl = `  ${f.name} : ${f.type},`;
    const note = `// @${f.offset}${f.doc ? `  ${f.doc}` : ""}`;
    return `${decl.padEnd(34)}${note}`;
  });
  return `// size ${s.size}, align ${s.align}\nstruct ${s.name} {\n${lines.join("\n")}\n}`;
}

function emitBinding(group: number, b: BindingDef): string {
  const head = `@group(${group}) @binding(${b.binding})`;
  let decl: string;
  switch (b.kind) {
    case "uniform":
      decl = `var<uniform> ${b.name} : ${b.wgslType};`;
      break;
    case "sampler":
      decl = `var ${b.name} : sampler;`;
      break;
    case "storage-read":
      decl = `var<storage, read> ${b.name} : ${b.wgslType};`;
      break;
  }
  const line = `${head} ${decl}`;
  return b.doc ? `${line.padEnd(78)}// ${b.doc}` : line;
}

/** Masks, flags and large bit values read better in hex; counts and shifts in decimal. */
const u32Literal = (name: string, v: number): string => {
  const bitsy = /_MASK$|_FLAG_|^NO_|_CULLED$/.test(name) || v >= 0x10000;
  return bitsy ? `0x${(v >>> 0).toString(16).toUpperCase()}u` : `${v}u`;
};

export function emitLayoutsWgsl(): string {
  const out: string[] = [
    "// GENERATED by src/data/LayoutsWgsl.ts from src/data/Layouts.ts. Do not edit.",
    `// Binding contract version ${BINDING_CONTRACT_VERSION}.`,
    "",
    emitStruct(FRAME),
    "",
    ...FRAME_BINDINGS.map((b) => emitBinding(GROUP_FRAME, b)),
    "",
    ...GRAPH_BINDINGS.map((b) => emitBinding(GROUP_GRAPH, b)),
    "",
    ...Object.entries(CONSTANTS).map(([k, v]) => `const ${k} : u32 = ${u32Literal(k, v)};`),
    "",
    ...OVERRIDES.map((o) => `override ${o.name} : ${o.type} = ${o.value};`),
    "",
    "// ---- Engine-internal (not public contract; may change between versions) ----",
    "",
    emitStruct(NODE_INSTANCE),
    "",
    emitStruct(CHUNK_BOUNDS),
    "",
    emitStruct(EDGE_CHUNK),
    "",
    ...Object.entries(EDGE_CONSTANTS).map(([k, v]) => `const ${k} : u32 = ${u32Literal(k, v)};`),
    "",
    emitStruct(LABEL_PARAMS),
    "",
    emitStruct(LABEL_CANDIDATE),
    "",
    emitStruct(LIVE_LABEL),
    "",
    ...Object.entries(LABEL_CONSTANTS).map(([k, v]) => `const ${k} : u32 = ${u32Literal(k, v)};`),
    "",
    ...Object.entries(ENGINE_CONSTANTS).map(([k, v]) => `const ${k} : u32 = ${u32Literal(k, v)};`),
    "",
    emitStruct(PICK_PARAMS),
    "",
    ...Object.entries(PICK_CONSTANTS).map(([k, v]) => `const ${k} : u32 = ${u32Literal(k, v)};`),
    "",
    emitStruct(HOVER_PARAMS),
    "",
  ];
  return out.join("\n");
}
